import "./globals.css";

import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";

import Providers from "@/app/providers";

const robotoMono = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by NATHAN DRAKE",
  title: "Flexbox 4 lyfe",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={robotoMono.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
